### ISSUE TITLE
Error while installing

### ISSUE THREAD

**Issue by itshasnaf** [LifeHack3r/Scavenger#1]
root@kali:/home/kali/Desktop/Scavenger# pip3 install -r requirements.txt
Collecting argparse
  Downloading argparse-1.4.0-py2.py3-none-any.whl (23 kB)
Collecting configparser
  Downloading configparser-5.0.0-py3-none-any.whl (22 kB)
Requirement already satisfied: requests in /usr/lib/python3/dist-packages (from -r requirements.txt (line 3)) (2.23.0)
Collecting jq
  Downloading jq-1.0.2-cp38-cp38-manylinux2010_x86_64.whl (532 kB)
     |████████████████████████████████| 532 kB 623 kB/s 
Collecting dnsgen
  Downloading dnsgen-1.0.4-py2.py3-none-any.whl (6.9 kB)
ERROR: Could not find a version that satisfies the requirement glob (from -r requirements.txt (line 6)) (from versions: none)
ERROR: No matching distribution found for glob (from -r requirements.txt (line 6))
root@kali:/home/kali/Desktop/Scavenger#

**Comment by RogueSMG** [comment]
Ah, I've made some changes. It should be working now!
